[build]
  functions = "netlify/functions"
  publish = "public"
  command = "echo 'Build complete'"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["react", "react-dom"]
