[build]
  command = "echo 'Build complete'"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["react", "react-dom"]

[redirects]
  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[environment]
  rolo_ai_key = "your-openai-api-key" # You already added this in Netlify UI
